runtime: java17
service: book-service
instance_class: F1

env_variables:
  SPRING_PROFILES_ACTIVE: production
  JAVA_OPTS: "-Xmx128m -Xms64m"

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8